### PR TITLE
great idea, would love to be a part

### PR DESCRIPTION
**Pull request by krumware**
:+1:

### CODE REVIEW

**Comment by mo-g** [comment]
[XKCD1296](https://xkcd.com/1296/) is a warning advisory, not a style guide! :stuck_out_tongue:

haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaands

**Comment by krumware** [comment]
I just got really excited, but now I realize I missed a golden opportunity to us 🖊 instead
Can do a new PR if necessary!

**Comment by mo-g** [comment]
`git rebase -i origin/master`

Then replace 'pick' with 'r' to edit your commit message.

Then, `git push origin -f`.

No need to create a new PR.

**Comment by Widdershin** [comment]
Thanks for the ✍️

**Pull request merged**
