### PR TITLE
removing my signature

### PR DESCRIPTION
**Pull request by vassudanagunta**
This seems to be an empty display of morality, as each signatory can interpret the Oath however suits them.

An oath that avoids taking principled stands so that it can be all things to all people isn't much of an oath.

If at least the oath hosted a dialog about what the oath means, that discussion would be very valuable in moving tech culture in a positive, morals over money direction. But issues raised get silenced or dismissed (see Issue #120). 

"It is difficult to get a man to understand something when his salary depends upon his not understanding it.” – Upton Sinclair

This is a big deal for me because I've dedicated my life toward social justice and fairness issues. The tech world, sadly, is too focused on money. 

Good luck.

### CODE REVIEW

**Comment by Widdershin** [comment]
Thanks for taking part in these conversations @vassudanagunta, I wish you all the best.

**Comment by bderiso** [comment]
Talk about “empty display of morality”, removing a signature with a catty response? I personally don’t see how that is constructive.

And requesting a dialog? That’s rich given your history.

**Comment by Widdershin** [comment]
Please refrain from making critical comments on other people's signatures or removals, I can't really see any good coming from that.

@vassudanagunta I'm sorry that you had a negative experience with your discussions here. I respect your viewpoint and wish you all the best.

**Comment by vassudanagunta** [comment]
@Widdershin Thank you. All the best to you too!

**Pull request merged**
