### PR TITLE
Added BASIC-style Tenet numbers.

### LINKED ISSUE #6: Tenets are not numbered
Like the [20 Precepts of Shotokan](http://wskc-jka.co.uk/shotokan/karate-principles/) and the [five tenets of the Dark Brotherhood](http://elderscrolls.wikia.com/wiki/Five_Tenets), all lists of tenets should be numbered for ease of reference.

Of course, for a *programmers* tenets, the numbers should be contextually appropriate.

### PR DESCRIPTION
**Pull request by mo-g**
Fixes #6. In style.

### CODE REVIEW

**Comment by Widdershin** [comment]
@mo-g thank you for making this pull request.

I'm in favour of numbering the tenets, but I'm not sure about the BASIC-style numbers. My concern is that new programmers might not be familiar with this numbering scheme, and that they might feel alienated by the use of what is effectively an in-joke.

I think my preference would be for a more traditional numbering scheme. Perhaps a zero indexed list, as a nod to programming with less risk of alienation?

What do you think?

**Comment by mo-g** [comment]
I think that's a fair comment. Give me two seconds, I'll edit and rebase.

**Comment by mo-g** [comment]
Note for latecomers - this PR originally proposed BASIC-style (10, 20, 30) Tenet numbers but was changed to 0-indexed for less injoke.

**Comment by Widdershin** [comment]
Much obliged @mo-g 😄

**Comment by mo-g** [comment]
Welcome. :grin:

**Pull request merged**
