### PR TITLE
Replace the terrible word "learnings"

### PR DESCRIPTION
**Pull request by eentzel**
Pet peeve of mine, but this is a bogus word :)

### CODE REVIEW

**Comment by mo-g** [comment]
Thanks for putting this together! :)

I think I prefer the originally suggested 'lessons' over 'knowledge'. What's your take, @Widdershin?

**Comment by mo-g** [comment]
This fixes #55, for the record.

**Comment by bazscott** [comment]
Thanks @eentzel, good work 👍

**Comment by Widdershin** [comment]
> I will respect the learnings of those programmers who came before me

To me, this reads as respecting the immense body of work that precedes us, not re-inventing the wheel and doing due diligence to see what prior solutions have been considered for a problem.

> I will respect the knowledge of those programmers who came before me

Whereas this to me reads as respecting the fact that all those prior programmers have a lot of knowledge, which almost feels like an appeal to seniority.

What do y'all think?

Is there a word we can use in place of `knowledge` or a modifier we can attach to indicate that it's less about respecting seniority for seniority's sake, but rather respecting the immense body of preceding work?

**Comment by Thrilleratplay** [comment]
@Widdershin Were you thinking some more along these lines?

> I will respect the knowledge and wisdom of those programmers who came before me, and share my experiences, both good and bad, what I learned from them with those to come.

There is are graybeards who legitimately seem to know everything but there is also [the story of Mel](http://www.catb.org/jargon/html/story-of-mel.html).

**Comment by Widdershin** [comment]
Hmmm, still doesn't feel quite right.

How about:

> I will respect the lessons learned by those who came before me, and share what I learn with those to come.

**Comment by eentzel** [comment]
I like that, @Widdershin — changed it in  44c0694.

**Comment by mo-g** [comment]
I'm getting an itchy merge-button finger. This looks good to me.

**Comment by Widdershin** [comment]
Merged  😊 thanks for helping.

**Comment by vassudanagunta** [comment]
I know this is late but for some reason I *just* got notification of this. 

It is important to understand that "lessons" is narrower than "learnings" or "knowledge". There are many things people learn or discover, many kinds of knowledge that aren't lessons learned. Is the narrower meaning the intent of this item?

To me this oath item is one of the most important, and as you can see from [my comment here](https://github.com/Widdershin/programmers-oath/issues/83#issuecomment-370195468) I had read it with a broader meaning than "lessons learned".

**Comment by mo-g** [comment]
> It is important to understand that "lessons" is narrower than "learnings" or "knowledge"

Not in this context. 'Learnings' is a recent word derived in corporate settings from the archaic singular noun 'Learning'. Otherwise, the word lessons is used in the exact same way. It does not in any way limit the way those lessons were learned, and does not in any way imply a setting such as 'classroom lessons'.

**Pull request merged**
