### PR TITLE
Adding thrilleratplay

### PR DESCRIPTION
**Pull request by Thrilleratplay**

### CODE REVIEW

**Comment by mo-g** [comment]
Any chance of squashing those into a single commit? :smiley:

**Comment by Widdershin** [comment]
Thanks for signing @Thrilleratplay 😄

**Comment by Widdershin** [comment]
@mo-g I've just been using the squash and merge button, saves a bit of trouble.

**Comment by Thrilleratplay** [comment]
@Widdershin Thanks.  I didn't notice at first and was a few minutes too late to squash.

**Pull request merged**
