### PR TITLE
Move humility/learning opportunities towards top

### LINKED ISSUE #37: Item 5 could be two items
The text in item 5 seems like two separate items. Both items are important, but they seem somewhat distinct. 

> 5. I will tread most carefully in matters of life or death. I will be humble and recognize that I will make mistakes.

The '*I will be humble and recognize that I will make mistakes.*' seems more directly related to item 3 '*I will not be ashamed to say "I don't know", and I will ask for help when I am stuck.*'

### PR DESCRIPTION
**Pull request by brylie**
Closes #37

Reorganized list slightly:

- move humility (and learning from mistakes) to early in list
  - learning from own mistakes precedes respecting respecting others' learning

### CODE REVIEW

**Comment by mo-g** [comment]
I'm not sure about this PR - it's a lot more sweeping than a fix for the issue in #37?

**Comment by Widdershin** [comment]
I'm in favour of splitting #5, but I'd like to first make that change as minimally as possible, and then we can consider the reordering of items.

How do you feel about that @brylie?

**Comment by brylie** [comment]
Sounds good. It just seems to flow naturally that by treating our mistakes as learning opportunities we would more readily appreciate/respect the lessons learned by others.

**Comment by brylie** [comment]
Opened a new PR #72

**Pull request closed without merging**
